---

- name: nginx_install
  hosts: nginx_server
  
  tasks:

   - name: install epel-release
     yum: name=epel-release state=present
   
   - name: install nginx
     yum: name=nginx state=latest

   - name: start nginx server
     service: name=nginx state=started
